In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler

df = pd.read_excel('Purchase_data_50_rows.xlsx')

nominal_data = df[['Customer_Type', 'Product_Category']].values
ordinal_data = df['Satisfaction_Level'].values
binary_data = df['Purchase_Decision'].values
numeric_data = df['Age'].values.reshape(-1, 1)

label_encoder = LabelEncoder()
nominal_data_encoded = label_encoder.fit_transform(nominal_data.ravel()).reshape(nominal_data.shape)

ordinal_encoder = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
ordinal_data_encoded = ordinal_encoder.fit_transform(ordinal_data.reshape(-1, 1))

scaler = StandardScaler()
numeric_data_standardized = scaler.fit_transform(numeric_data)

combined_data = np.column_stack((nominal_data_encoded, ordinal_data_encoded, binary_data, numeric_data_standardized))

dissimilarity_nominal = pairwise_distances(nominal_data_encoded, metric='hamming')
np.fill_diagonal(dissimilarity_nominal, 0)
dissimilarity_nominal = np.tril(dissimilarity_nominal)

print("Dissimilarity Matrix for Nominal Data:")
print(dissimilarity_nominal)

dissimilarity_ordinal = pairwise_distances(ordinal_data_encoded.reshape(-1, 1), metric='euclidean')
np.fill_diagonal(dissimilarity_ordinal, 0)
dissimilarity_ordinal = np.tril(dissimilarity_ordinal)

print("\nDissimilarity Matrix for Ordinal Data:")
print(dissimilarity_ordinal)

dissimilarity_binary = pairwise_distances(binary_data.reshape(-1, 1), metric='hamming')
np.fill_diagonal(dissimilarity_binary, 0)
dissimilarity_binary = np.tril(dissimilarity_binary)

print("\nDissimilarity Matrix for Binary Data:")
print(dissimilarity_binary)

dissimilarity_numeric = pairwise_distances(numeric_data_standardized, metric='euclidean')
np.fill_diagonal(dissimilarity_numeric, 0)
dissimilarity_numeric = np.tril(dissimilarity_numeric)

print("\nDissimilarity Matrix for Numeric Data:")
print(dissimilarity_numeric)


Dissimilarity Matrix for Nominal Data:
[[0.  0.  0.  ... 0.  0.  0. ]
 [1.  0.  0.  ... 0.  0.  0. ]
 [1.  0.5 0.  ... 0.  0.  0. ]
 ...
 [0.  1.  1.  ... 0.  0.  0. ]
 [1.  0.5 0.  ... 1.  0.  0. ]
 [0.5 1.  0.5 ... 0.5 0.5 0. ]]

Dissimilarity Matrix for Ordinal Data:
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]]

Dissimilarity Matrix for Binary Data:
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]]

Dissimilarity Matrix for Numeric Data:
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [1.3622644  1.3622644  0.         ... 0.         0.         0.        ]
 ...
 [0.94310612 0.94310612 0.41915828 ... 0.         0.         0.        ]
 [0.41915828 0.41915828 1.78142267 ... 1.